#DEFINE "FDREDWC", "3"
#DEFINE "FDINDEX", "5"
#DEFINE "FDMOTE0", "11"
#DEFINE "FDDRVS1", "18"
#DEFINE "FDDRVS0", "19"
#DEFINE "FDMOTE1", "21"
#DEFINE "FDDIR", "23"
#DEFINE "FDSTEP", "27"
#DEFINE "FDWDATA", "28"
#DEFINE "FDWEN", "31"
#DEFINE "FDTRK00", "32"
#DEFINE "FDWPT", "33"
#DEFINE "FDRDATA", "35"
#DEFINE "FDSIDE1", "36"
#DEFINE "FDDSKCH", "38"

Sub fdSetup
    SetPin FDREDWC, DOUT: Pin(FDREDWC) = 0
    SetPin FDMOTE0, DOUT: Pin(FDMOTE0) = 1
    SetPin FDDRVS1, DOUT: Pin(FDDRVS1) = 1
    SetPin FDDRVS0, DOUT: Pin(FDDRVS0) = 0
    SetPin FDMOTE1, DOUT: Pin(FDMOTE1) = 1
    SetPin FDDIR, DOUT: Pin(FDDIR) = 1
    SetPin FDSTEP, DOUT: Pin(FDSTEP) = 1
    SetPin FDWDATA, DOUT: Pin(FDWDATA) = 1
    SetPin FDWEN, DOUT: Pin(FDWEN) = 1
    SetPin FDSIDE1, DOUT: Pin(FDSIDE1) = 0
    SetPin FDINDEX, DIN
    SetPin FDTRK00, DIN
    SetPin FDWPT, DIN
    SetPin FDRDATA, DIN
    SetPin FDDSKCH, DIN
End Sub

fdSetup
Pause 200
Print Pin(FDINDEX), Pin(FDTRK00), Pin(FDWPT), Pin(FDRDATA), Pin(FDDSKCH)
