#DEFINE "CLOCKPIN","3"
#DEFINE "ENABLEPIN","5"
#DEFINE "SERIALPIN","7"
#DEFINE "LATCHPIN","11"
#DEFINE "Motor3Pin","12"
#DEFINE "M3A","1"
#DEFINE "M3B","64"
#INCLUDE "A:/ShiftOut.inc"

ShiftInit(13,LATCHPIN,CLOCKPIN,ENABLEPIN,SERIALPIN)
ShiftOut(LATCHPIN,CLOCKPIN,ENABLEPIN,SERIALPIN,M3B)
PWM 1,1000,50
Pause 4000
PWM 1, STOP
